package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TestCliente generated by hbm2java
 */
public class TestCliente implements java.io.Serializable {

	private Integer idCliente;
	private long identifiacion;
	private String nombres;
	private String apellidos;
	private String direccion;
	private String telefono;
	private String email;
	private Set<TestFactura> testFacturas = new HashSet<TestFactura>(0);

	public TestCliente() {
	}

	public TestCliente(long identifiacion, String nombres, String apellidos, String direccion) {
		this.identifiacion = identifiacion;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.direccion = direccion;
	}

	public TestCliente(long identifiacion, String nombres, String apellidos, String direccion, String telefono,
			String email, Set<TestFactura> testFacturas) {
		this.identifiacion = identifiacion;
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.testFacturas = testFacturas;
	}

	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	public long getIdentifiacion() {
		return this.identifiacion;
	}

	public void setIdentifiacion(long identifiacion) {
		this.identifiacion = identifiacion;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<TestFactura> getTestFacturas() {
		return this.testFacturas;
	}

	public void setTestFacturas(Set<TestFactura> testFacturas) {
		this.testFacturas = testFacturas;
	}

}
