package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TestProducto generated by hbm2java
 */
public class TestProducto implements java.io.Serializable {

	private Integer idProducto;
	private String codigo;
	private String nombre;
	private BigDecimal valorUnidad;
	private int stock;
	private Set<TestFacturaDetalle> testFacturaDetalles = new HashSet<TestFacturaDetalle>(0);

	public TestProducto() {
	}

	public TestProducto(String codigo, String nombre, BigDecimal valorUnidad, int stock) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.valorUnidad = valorUnidad;
		this.stock = stock;
	}

	public TestProducto(String codigo, String nombre, BigDecimal valorUnidad, int stock,
			Set<TestFacturaDetalle> testFacturaDetalles) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.valorUnidad = valorUnidad;
		this.stock = stock;
		this.testFacturaDetalles = testFacturaDetalles;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getValorUnidad() {
		return this.valorUnidad;
	}

	public void setValorUnidad(BigDecimal valorUnidad) {
		this.valorUnidad = valorUnidad;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public Set<TestFacturaDetalle> getTestFacturaDetalles() {
		return this.testFacturaDetalles;
	}

	public void setTestFacturaDetalles(Set<TestFacturaDetalle> testFacturaDetalles) {
		this.testFacturaDetalles = testFacturaDetalles;
	}

}
