package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TestFactura generated by hbm2java
 */
public class TestFactura implements java.io.Serializable {

	private int idFactura;
	private TestCliente testCliente;
	private Date fechaVenta;
	private BigDecimal valorTotal;
	private Set<TestFacturaDetalle> testFacturaDetalles = new HashSet<TestFacturaDetalle>(0);

	public TestFactura() {
	}

	public TestFactura(int idFactura, TestCliente testCliente, Date fechaVenta, BigDecimal valorTotal) {
		this.idFactura = idFactura;
		this.testCliente = testCliente;
		this.fechaVenta = fechaVenta;
		this.valorTotal = valorTotal;
	}

	public TestFactura(int idFactura, TestCliente testCliente, Date fechaVenta, BigDecimal valorTotal,
			Set<TestFacturaDetalle> testFacturaDetalles) {
		this.idFactura = idFactura;
		this.testCliente = testCliente;
		this.fechaVenta = fechaVenta;
		this.valorTotal = valorTotal;
		this.testFacturaDetalles = testFacturaDetalles;
	}

	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

	public TestCliente getTestCliente() {
		return this.testCliente;
	}

	public void setTestCliente(TestCliente testCliente) {
		this.testCliente = testCliente;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Set<TestFacturaDetalle> getTestFacturaDetalles() {
		return this.testFacturaDetalles;
	}

	public void setTestFacturaDetalles(Set<TestFacturaDetalle> testFacturaDetalles) {
		this.testFacturaDetalles = testFacturaDetalles;
	}

}
