package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Id;

/**
 * TestCliente generated by hbm2java
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "test_cliente")
public class TestCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8201559290949823837L;
	
	@Id
	@Column(name = "idCliente")
	private Integer id_cliente;

	@Column(name = "Identifiacion")
	private long Identifiacion;

	@Column(name = "nombres")
	private String Nombres;
	
	@Column(name = "apellidos")
	private String Apellidos;
	
	@Column(name = "direccion")
	private String Direccion;
	
	@Column(name = "telefono")
	private String Telefono;
	
	@Column(name = "email")
	private String Email;
	
	
	public TestCliente() {
	}

	public TestCliente(long Identifiacion, String Nombres, String Apellidos, String Direccion,String Telefono,String Email ) {
		this.Identifiacion = Identifiacion;
		this.Nombres = Nombres;
		this.Apellidos = Apellidos;
		this.Direccion = Direccion;
		this.Telefono = Telefono;
		this.Email=Email;
	}

	
	public Integer getid_cliente() {
		return this.id_cliente;
	}

	public void setid_cliente(Integer id_cliente) {
		this.id_cliente = id_cliente;
	}

	public long getIdentifiacion() {
		return this.Identifiacion;
	}

	public void setIdentifiacion(long identifiacion) {
		this.Identifiacion = Identifiacion;
	}

	public String getNombres() {
		return this.Nombres;
	}

	public void setNombres(String Nombres) {
		this.Nombres = Nombres;
	}

	public String getApellidos() {
		return this.Apellidos;
	}

	public void setApellidos(String Apellidos) {
		this.Apellidos = Apellidos;
	}

	public String getDireccion() {
		return this.Direccion;
	}

	public void setDireccion(String Direccion) {
		this.Direccion = Direccion;
	}

	public String getTelefono() {
		return this.Telefono;
	}

	public void setTelefono(String Telefono) {
		this.Telefono = Telefono;
	}

	public String getEmail() {
		return this.Email;
	}

	public void setEmail(String Email) {
		this.Email = Email;
	}



}
