package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TestFactura generated by hbm2java
 */
@javax.persistence.Entity
@javax.persistence.Table(name = "test_factura")
public class TestFactura implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5809469292916317571L;
	/**
	 * 
	 */
	@Id
	@Column(name = "idFactura")
	private int idFactura;	
	
	@OneToOne(cascade=CascadeType.ALL)
	@JoinColumn(name="idCliente")
	private TestCliente testCliente;
	
	@Column(name = "FechaVenta")
	private Date fechaVenta;
	
	@Column(name = "valorTotal")
	private BigDecimal valorTotal;
	
	
	public TestFactura() {
	}

	public TestFactura(int idFactura, TestCliente testCliente, Date fechaVenta, BigDecimal valorTotal) {
		this.idFactura = idFactura;
		this.testCliente = testCliente;
		this.fechaVenta = fechaVenta;
		this.valorTotal = valorTotal;
	}

	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

	public TestCliente getTestCliente() {
		return this.testCliente;
	}

	public void setTestCliente(TestCliente testCliente) {
		this.testCliente = testCliente;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	

}
