package sv.com.model;
// Generated 18/11/2020, 7:41:26 p.�m. by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TestProducto generated by hbm2java
 */

@Entity
@Table(name = "test_producto")
public class TestProducto implements java.io.Serializable {

	@Id
	@Column(name = "IdProducto")
	private Integer idProducto;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "valorUnidad")
	private BigDecimal valorUnidad;
	
	@Column(name = "stock")
	private int stock;
	
	
	public TestProducto() {
	}

	public TestProducto(String codigo, String nombre, BigDecimal valorUnidad, int stock) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.valorUnidad = valorUnidad;
		this.stock = stock;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public BigDecimal getValorUnidad() {
		return this.valorUnidad;
	}

	public void setValorUnidad(BigDecimal valorUnidad) {
		this.valorUnidad = valorUnidad;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}
}
